import pandas as pd
from datetime import datetime,timedelta
from pyproj import Transformer

GPS_EPOCH = datetime(1980, 1, 6) # GPS epoch start date
def gpstime_to_datetime(gps_week, gps_seconds):
    """
    Convert GPS week and seconds to a datetime object.
    
    Parameters:
    gps_week: The GPS week number.
    gps_seconds: The number of seconds into the GPS week.

    Returns:
    A datetime object representing the corresponding date and time.
    """

    gps_time = GPS_EPOCH + timedelta(weeks=gps_week) + timedelta(seconds=gps_seconds)
    return gps_time

def datetime_to_gpstime(dt):
    """Convert datetime → (gps_week, seconds_of_week)"""
    delta = dt - GPS_EPOCH
    gps_week = delta.days // 7
    seconds_of_week = (delta - timedelta(weeks=gps_week)).total_seconds()
    return gps_week, seconds_of_week

def etrs89_ecef_to_itrf(df, obs_epoch=2024.003):
    """
    Convert ETRF2000 ECEF coordinates to ITRF (WGS84) by removing
    the accumulated Eurasian plate motion since the ETRS89 reference epoch (1989.0).

    Plate velocities for Denmark (BUDD00DNK area) in ITRF2014, m/yr:
    Source: EUREF Permanent Network / ITRF velocity field for Scandinavia
    """
    dt = obs_epoch - 1989.0  # = 35.003 years

    # Eurasian plate velocity at Denmark in ITRF2014 ECEF (m/yr)
    # These are site-specific values for the Copenhagen/Zealand area
    VX = -0.0141
    VY =  0.0187
    VZ =  0.0124

    df = df.copy()
    df["X-ECEF"] += VX * dt   # ≈ −0.494 m
    df["Y-ECEF"] += VY * dt   # ≈ +0.655 m
    df["Z-ECEF"] += VZ * dt   # ≈ +0.434 m

    print(f"ETRF2000 → ITRF correction applied over {dt:.3f} years:")
    print(f"  ΔX = {VX*dt:+.4f} m")
    print(f"  ΔY = {VY*dt:+.4f} m")
    print(f"  ΔZ = {VZ*dt:+.4f} m")
    print(f"  |Δ| = {(VX*dt)**2 + (VY*dt)**2 + (VZ*dt)**2:.4f}^0.5 = {((VX*dt)**2 + (VY*dt)**2 + (VZ*dt)**2)**0.5:.4f} m")

    return df

def read_imu_csv(file_path, gps_week=None):
    # see https://geodesy.noaa.gov/CORS/resources/gpscals.shtml
    try:
        df = pd.read_csv(file_path, sep=r"\s+")
        if gps_week is not None:
            df['datetime'] = df.apply(lambda row: gpstime_to_datetime(gps_week, row['Time']), axis=1)
        return df
        
    except Exception as e:
        print(f"Error reading the IMU CSV file: {e}")
        return None

def read_ground_truth_csv(file_path,gps_week=None):
    try:
        header = [
            'GPSTime', 'X-ECEF', 'Y-ECEF', 'Z-ECEF',
            'Heading', 'Pitch', 'Roll',
            'VX-ECEF', 'VY-ECEF', 'VZ-ECEF', 'UTCTime'
        ]

        # Read file, skipping header lines
        df = pd.read_csv(
            file_path,
            sep=r"\s+",
            skiprows=21,
            names=header,
            engine="python"  # needed for flexible parsing
        )

        # Convert everything to float
        df = df.astype(float)

        # Convert to datetime object
        if gps_week is not None:
            df['datetime'] = df.apply(lambda row: gpstime_to_datetime(gps_week, row['GPSTime']), axis=1)
    
        # Convert from ETRS89 to EPSG
        df = etrs89_ecef_to_itrf(df, obs_epoch=2024.003)

        return df

    except Exception as e:
        print(f"Error reading the ground truth CSV file: {e}")
        return None

def read_spp_csv(file_path):
    try:
        df = pd.read_csv(file_path)

        # Parse datetime column
        df["datetime"] = pd.to_datetime(df["datetime"])

        # Convert to GPS time
        gps_times = df["datetime"].apply(datetime_to_gpstime)

        df["gps_week"] = gps_times.apply(lambda x: x[0])
        df["GPSTime"] = gps_times.apply(lambda x: x[1])

        # Convert numeric columns
        numeric_cols = [
            "X-ECEF", "Y-ECEF", "Z-ECEF",
            "cdt", "variance",
            "VX-ECEF", "VY-ECEF", "VZ-ECEF"
        ]
        df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce")

        return df

    except Exception as e:
        print(f"Error reading SPP CSV file: {e}")
        return None

def read_pos_file(pos_file_path):
    """
    Reads a POS file generated by RTKLIB's RTKPOST and returns a DataFrame.

    Args:
        pos_file_path (str): Path to the POS file.
        set_time_index (bool): If True, use time as DataFrame index.

    Returns:
        pd.DataFrame: DataFrame containing parsed POS data.
    """

    rows = []

    with open(pos_file_path, "r") as f:
        for line in f:

            # Skip header/comments
            if line.startswith("%") or len(line.strip()) == 0:
                continue

            parts = line.split()

            # Ensure enough columns exist
            if len(parts) < 15:
                continue

            try:
                rows.append({
                    "datetime": parts[0] + " " + parts[1],
                    "X-ECEF": float(parts[2]),
                    "Y-ECEF": float(parts[3]),
                    "Z-ECEF": float(parts[4]),
                    "Q": int(parts[5]),
                    "ns": int(parts[6]),
                    "sdn": float(parts[7]),
                    "sde": float(parts[8]),
                    "sdu": float(parts[9]),
                    "sdne": float(parts[10]),
                    "sdeu": float(parts[11]),
                    "sdun": float(parts[12]),
                    "age": float(parts[13]),
                    "ratio": float(parts[14]),
                })
            except ValueError:
                # Skip corrupted lines
                continue

        df = pd.DataFrame(rows)
        df["datetime"] = pd.to_datetime(df["datetime"])

        # Convert to GPS time
        gps_times = df["datetime"].apply(datetime_to_gpstime)

        df["gps_week"] = gps_times.apply(lambda x: x[0])
        df["GPSTime"] = gps_times.apply(lambda x: x[1])

    
    return df
 
if __name__ == "__main__":
    csv_file = r"data/run2_imu.txt"
    ground_truth_file = r"data/run2_groundtruth.txt"
    spp_file        = r"data/run2_spp_solution.csv"

    imu_data = read_imu_csv(csv_file, gps_week=2415) 
    print(imu_data.head())
    print(imu_data.columns)
    print(imu_data.shape)

    ground_truth_data = read_ground_truth_csv(ground_truth_file, gps_week=2415)

    print(ground_truth_data.head())
    print(ground_truth_data.columns)
    print(ground_truth_data.shape)